"""Sync models

Revision ID: 38325d01586b
Revises: 001_initial
Create Date: 2026-06-21 22:17:48.389755
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38325d01586b'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('exam_sessions', sa.Column('warning_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_sessions', sa.Column('termination_reason', sa.String(length=500), nullable=True))
    op.add_column('exam_sessions', sa.Column('current_gear', sa.Integer(), nullable=False))
    op.add_column('exam_sessions', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_sessions', sa.Column('gear_4_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_sessions', sa.Column('trust_score', sa.Float(), nullable=False))
    op.alter_column('exam_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'paused', 'completed', 'terminated', name='sessionstatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::sessionstatus"))
    op.alter_column('exam_sessions', 'network_tier',
               existing_type=postgresql.ENUM('tier_1', 'tier_2', 'tier_3', 'tier_4', name='networktier'),
               nullable=False,
               existing_server_default=sa.text("'tier_1'::networktier"))
    op.alter_column('exam_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('exams', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('exams', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('exams', 'fl_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('exams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('gaze_snapshots', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('proctor_reviews', 'verdict',
               existing_type=postgresql.ENUM('confirmed', 'false_positive', 'pending', name='reviewverdict'),
               nullable=False,
               existing_server_default=sa.text("'pending'::reviewverdict"))
    op.alter_column('proctor_reviews', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('proctor_reviews', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('proctor_reviews', 'verdict',
               existing_type=postgresql.ENUM('confirmed', 'false_positive', 'pending', name='reviewverdict'),
               nullable=True,
               existing_server_default=sa.text("'pending'::reviewverdict"))
    op.alter_column('gaze_snapshots', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('exams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('exams', 'fl_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('exams', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('exams', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('exam_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('exam_sessions', 'network_tier',
               existing_type=postgresql.ENUM('tier_1', 'tier_2', 'tier_3', 'tier_4', name='networktier'),
               nullable=True,
               existing_server_default=sa.text("'tier_1'::networktier"))
    op.alter_column('exam_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'paused', 'completed', 'terminated', name='sessionstatus'),
               nullable=True,
               existing_server_default=sa.text("'active'::sessionstatus"))
    op.drop_column('exam_sessions', 'trust_score')
    op.drop_column('exam_sessions', 'gear_4_start')
    op.drop_column('exam_sessions', 'last_heartbeat_at')
    op.drop_column('exam_sessions', 'current_gear')
    op.drop_column('exam_sessions', 'termination_reason')
    op.drop_column('exam_sessions', 'warning_issued_at')
    op.alter_column('detection_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
